# Generated by Django 2.1.5 on 2019-02-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_autorepairshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_policy_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_behind_payment',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
