# Generated by Django 2.1.5 on 2019-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190204_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accident_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
