# Generated by Django 2.1.5 on 2019-02-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190208_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['priority', '-id']},
        ),
    ]
