# Generated by Django 2.1.5 on 2019-02-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190212_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['ordering'], 'verbose_name_plural': 'order statuses'},
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
