# Generated by Django 2.1.5 on 2019-02-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190212_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_attachment', to='orders.Order'),
        ),
    ]
